### ISSUE TITLE
Joint Training

### ISSUE THREAD

**Issue by haterbreaker** [AlanDongMu/TimeGAN_PytorchRebuild#1]
Hi, thanks for your great work!
I wonder if you miss "self.E_loss.backward()" after this line:
https://github.com/AlanDongMu/TimeGAN_PytorchRebuild/blob/master/timegan.py#L88C14-L88C14

**Comment by AlanDongMu** [comment]
Yes, you are right, it's a mistak. Thanks for the remindering me!

**Comment by AlanDongMu** [comment]
Yes, you are right, it's a mistak. Thanks for reminding me!
