### ISSUE TITLE
How can I get the new generated data (with .csv format)?

### ISSUE THREAD

**Issue by Randwluo** [AlanDongMu/TimeGAN_PytorchRebuild#3]
Sorry for my naive question, I am a beginner of deeplearning.
When I run your code successfully, there is only PCA and t-sne test image in folder ''output'' .
So how can I get the new generated data with .csv format?
Thank u very much!

**Comment by AlanDongMu** [comment]
The generated data can be found in run.py,
https://github.com/AlanDongMu/TimeGAN_PytorchRebuild/blob/9cab6ea292cb1a498a1880f79f05a3e1981cef35/run.py#L78
but it hasn’t been saved, and not a .csv format as well.
If you want to get it just like the format of the ori-data, you may also de-standardizing it by original scale of ori_data. The scale of ori-data can be found in data_loading.py. 
You may do it yourself, or you should wait for few days until I am free to update it.

**Comment by Randwluo** [comment]
Thank you for your reply! 
I will try to figure it out by myself first( but still wanna to see your updating : )

**Comment by Randwluo** [comment]
> The generated data can be found in run.py,
> 
> https://github.com/AlanDongMu/TimeGAN_PytorchRebuild/blob/9cab6ea292cb1a498a1880f79f05a3e1981cef35/run.py#L78
> 
> 
> but it hasn’t been saved, and not a .csv format as well.
> If you want to get it just like the format of the ori-data, you may also de-standardizing it by original scale of ori_data. The scale of ori-data can be found in data_loading.py.
> You may do it yourself, or you should wait for few days until I am free to update it.

I've already get the .csv data.
Thank u again!
